version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
  gigmaster:
    container_name: gigmaster
    image: ghcr.io/ronsh909/gigmaster:latest
    env_file: .env
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo

volumes:
  mongodb:
