name: main
on:
  push:
    tags: 
      - '**'
    
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          tags: ghcr.io/ronsh909/gigmaster:${{ github.sha }}
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    environment: lahoh-shitrit
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:
      - name: remote docker-compose up via ssh
        uses: appleboy/ssh-action@v0.1.5
        env:
          APPTOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.SSH_USER }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          WORKDIR: ${{ secrets.WORKDIR }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          envs: APPTOKEN,USERNAME,TELEGRAM_TOKEN,WORKDIR
          script: |
            echo $APPTOKEN | docker login ghcr.io -u $USERNAME --password-stdin
            echo $WORKDIR
            cd $WORKDIR
            git pull --no-ff
            docker compose pull
            TELEGRAM_TOKEN=$TELEGRAM_TOKEN docker compose up -d
