name: build & test
on:
  push:
    tags: 
      - '**'
    
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/ronsh909/gigmaster:${{ github.sha }}
            ghcr.io/ronsh909/gigmaster:latest
  
  deploy_test:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    environment: lahoh-shitrit
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:
      - name: remote docker-compose up via ssh
        uses: appleboy/ssh-action@v0.1.4
        env:
          APPTOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.SSH_USER }}
          TEST_WORKDIR: ${{ secrets.TEST_WORKDIR }}
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          envs: APPTOKEN,USERNAME,TEST_WORKDIR,SHA
          script: |
            echo $APPTOKEN | docker login ghcr.io -u $USERNAME --password-stdin
            cd $TEST_WORKDIR
            git pull --ff-only
            git checkout $SHA 
            docker compose -f ./testing-docker-compose.yaml pull
            docker compose -f ./testing-docker-compose.yaml up -d
